### ISSUE TITLE
(feat): Enhance Hero Section UI for mobile

### ISSUE THREAD

**Issue by janasounak** [Arindam200/makaut_buddy#101]
## Issue Title

> (feat): Enhance Hero Section UI for mobile

## Issue Description
> The rotating earth in mobile version is looking odd due to some padding

## Expected Behavior
>The padding should be zero so that the section line of the earth image is aligned with screen's edge 

## Actual Behavior
>the padding isn't zero

![WhatsApp Image 2024-02-06 at 22 28 51_e3206603](https://github.com/Arindam200/makaut_buddy/assets/82273357/b0148bbd-2d14-455d-9f12-1d6e7174cdcf)

**Comment by Arindam200** [comment]
Fixed
