### ISSUE TITLE
Modification in Chemistry-I

### ISSUE THREAD

**Issue by Aindrila-biswas** [Arindam200/makaut_buddy#103]
## Issue Title

> Modification in Chemistry-I

## Issue Description
> Add Chemistry 1st semester resources in "src/app/components/Tabs/Data.jsx"

Note:

The Format will be like this:
          {       
            key: 00 , // the next number
            heading: "The Title",
            description:
              "add a small description.",
            link: "https://www.youtube.com/xyz",
          },

**Comment by Aindrila-biswas** [comment]
Please assign me in this section to work.

**Comment by TamojitMandal** [comment]
I want to work on this section with @Aindrila-biswas

**Comment by suchanaGhosh** [comment]
I want to work on this section with @TamojitMandal @Aindrila-biswas

**Comment by TanayRoy18** [comment]
I want to work on this section with @Aindrila-biswas @TamojitMandal & @suchanaGhosh
