### ISSUE TITLE
Arrangement of Engineering drawing resources

### ISSUE THREAD

**Issue by Aindrila-biswas** [Arindam200/makaut_buddy#105]
## Issue Title

> Arrangement of Engineering drawing resources

## Issue Description
> To arrange the video resources of Engineering Graphics and Drawing in order.

**Comment by Aindrila-biswas** [comment]
i want to work in this section. Please assign me.

**Comment by tanu-bisui** [comment]
I want to work in this section with aindrila. Please assign me.

**Comment by Aindrila-biswas** [comment]
This issue has been resolved.
