### ISSUE TITLE
(feat):Adding new video in basic Electrical & Electronics section

### ISSUE THREAD

**Issue by rayAritra** [Arindam200/makaut_buddy#106]
## Issue Title

> *provide a descriptive/informative title. Use "(feat):" for enhancement requests. Use "(bug):" for bugs/defects/corrections.*

## Issue Description
> *provide a brief description of the issue*

## Expected Behavior
> *what is the **expected** behavior?*

## Actual Behavior
> *what is the **actual** behavior?*

## Steps to Reproduce 
> *provide relevant steps and/or prerequisites required to reproduce this issue.*

1.
2.
3.

## Version Information
> *Provide the version information.*

**Comment by OlibhiaGhosh** [comment]
I would like to work on this issue
