### ISSUE TITLE
[Feat:] Adding PYQs in each Section of BTECH CSE 1st Sem

### ISSUE THREAD

**Issue by RitochitGhosh** [Arindam200/makaut_buddy#107]
## Issue Title

> (feat): PYQs of each Subject of BTECH CSE 1st Sem.

## Issue Description
>  As this website provides a one-step solution to students, It's important for our website to have PYQs for each subject. So that they get a brief idea about the type of questions asked in exams.

## Steps to Reproduce 
> Here are 2 step solution of the issue I raised:

1. Go to makaut_buddy/ src/ app/ components/ Tabs/ Data.jsx
2. Find the respective position of each subject and add PYQs

**Comment by tanu-bisui** [comment]
I would like to work on this issue.
