### ISSUE TITLE
(docs): Improve Readme 

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#12]
## Description: 

 The current Readme is auto-generated and lacks user-friendliness.

### Objective : 
Customize the Readme to make it more contributor-friendly.

### Tasks:
  1. Review existing Readme and identify areas for improvement.
  2. Organize and structure the Readme for better readability.
  3. Add clear instructions for contributors on how to get started.
  4. Mention ways to contact and communicate with the project maintainers.

**Comment by tushar1-000** [comment]
Hi @Arindam200 I want to work on this issue. So kindly assign this issue to me.

**Comment by Arindam200** [comment]
@tushar1-000 Go ahead

**Comment by tushar1-000** [comment]
Hi I have submitted the pull request you can check it.
