### ISSUE TITLE
[FEAT]: Enhance Tab component

### ISSUE THREAD

**Issue by OlibhiaGhosh** [Arindam200/makaut_buddy#127]
## Title
Enhance Tab component

## Additional info
Adding the required features that are required to show just below the Tabs when we toggle them

## Issue
Search bar and search options are seen together even when we click on any of the above tabs</br>
**Screenshot**
![image](https://github.com/Arindam200/makaut_buddy/assets/147382643/f123abb5-8f2a-4355-8693-d5f29fc1506f)

**Comment by OlibhiaGhosh** [comment]
I would like to work on this issue

**Comment by Arindam200** [comment]
Go Ahead!
