### ISSUE TITLE
[Fix] : Align the profile icon in navbar

### ISSUE THREAD

**Issue by tanu-bisui** [Arindam200/makaut_buddy#139]
## Issue Title

Align the profile icon in navbar

## Issue Description

After signing up , in navbar of the home page the profile icon is not aligned perfectly.

## Issue Screenshot

![image](https://github.com/Arindam200/makaut_buddy/assets/152421998/629a9edc-c7fb-4c27-9151-6272f6cca430)

**Comment by Sky-De** [comment]
@Arindam200 hi, assign this to me, thanks

**Comment by Arindam200** [comment]
@Sky-De Go Ahead!

**Comment by OlibhiaGhosh** [comment]
I would like to work on this!
