### ISSUE TITLE
(feat): Add Back Button to Dashboard Page

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#14]
## Description
Currently, users navigating within the Dashboard have no convenient way to return to the previous page or step in their workflow. Adding a Back button will provide a seamless and intuitive way for users to backtrack and improve overall usability.

### Design Demo: 
Refer to the design file demo [here](https://www.figma.com/file/NXmDxbLgtpXVT6ZMhAVax7/MAKAUT-Buddy?type=design&node-id=0%3A1&mode=design&t=o6mNGm4jEqcvQyWz-1) for styling and placement guidance.

### Contributors.md: 

Check the contributors.md file for project structure and coding guidelines.

Your contributions are welcomed!

**Comment by mehulrnsit** [comment]
Hi @Arindam200 I would like to take up this

**Comment by Arindam200** [comment]
Go Ahead @mehulrnsit !
