### ISSUE TITLE
[ FIX ] : Add a loading sign till the globe image load 

### ISSUE THREAD

**Issue by tanu-bisui** [Arindam200/makaut_buddy#140]
## Issue Title
Add a loading sign till the globe image load

## Issue Description
The globe takes a little bit more time to load so add a loading sign till the globe load properly.

**Comment by GeorgiosDrivas** [comment]
Hello! @Arindam200 I would like to work on this issue.

**Comment by Arindam200** [comment]
Go Ahead @GeorgiosDrivas
