### ISSUE TITLE
feat: Set Default theme as Dark

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#143]
## Description
We need to set the default theme of this project to Dark. This change should ensure that even if the user's default theme is Light, the project will still display in Dark mode.

## Acceptance Criteria
1. The default theme of the project should be Dark.
2. The theme should remain Dark even if the user's system or browser default theme is set to Light.
3. Ensure that all components and pages are correctly styled in Dark mode.
4. Update any relevant documentation to reflect this change.

#### Steps to Implement
1. Update the theme configuration in the project settings to set Dark as the default theme.
2. Override any user-specific theme settings to ensure the project always uses Dark mode.
3. Test the application to ensure all elements are properly styled in Dark mode.
4. Update documentation and notify the team of this change.

#### Additional Information
- Please ensure that this change does not affect the functionality of the application.
- Consider adding a toggle option for users to switch themes if needed in the future.

**Comment by Asin-Junior-Honore** [comment]
hey @Arindam200 
can you assign this to me please🥲

**Comment by Arindam200** [comment]
Sure, Go ahead @Asin-Junior-Honore

**Comment by Asin-Junior-Honore** [comment]
@Arindam200 am having issues try to get the values for this environment varables 
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY= YOUR_PUBLISHABLE_KEY
CLERK_SECRET_KEY= YOUR_CLERK_SECRET_KEY
and the clerk link put in the readme documentaion  is not opening at all

**Comment by Arindam200** [comment]
Fixed #144
