### ISSUE TITLE
Title: Update Creator Names Formatting in Footer section

### ISSUE THREAD

**Issue by Asin-Junior-Honore** [Arindam200/makaut_buddy#145]
I noticed that in the Footer section, one of the creator's names is joined together with "and." To improve clarity and readability, I propose updating the formatting to separate each creator's name.

Current Formatting:

Created with love ❤️ by Swapnoneel Saha, Arindam Majumderand Samyabrata Maji

Proposed Formatting:

Created with love ❤️ by Swapnoneel Saha, Arindam Majumder, and Samyabrata Maji
This adjustment will ensure that all creators' names are properly distinguished, contributing to a more polished presentation of the project's creators.

**Comment by Arindam200** [comment]
Go Ahead
