### ISSUE TITLE
(fix): Navbar navigation fixes

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#15]
## Issue Description:
The current navigation behavior in the navbar is not functioning as expected. When clicking on the "Features" link, it should smoothly navigate to the Features section on the page. However, it is currently pointing to "/#" instead, which does not provide the desired navigation experience.

### Expected Behavior:
- Clicking on "Features" in the navbar should scroll smoothly to the Features section on the page.

### Actual Behavior:
- Clicking on "Features" in the navbar currently navigates to "/#" instead of scrolling to the Features section.

**Comment by Ryan-Maddock-96** [comment]
Hello! Could I take this issue please :)

**Comment by Arindam200** [comment]
Go Ahead @Ryan-Maddock-96

**Comment by Ryan-Maddock-96** [comment]
@Arindam200 PR created :)
