### ISSUE TITLE
bug: Incorrect Alignment of Radio Buttons in Dashboard

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#157]
## Description
The radio buttons in the Dashboard are not aligned correctly. This issue appears to be caused by Tailwind CSS classes being overwritten by Material-UI CSS classes. 

## Steps to Reproduce
1. Navigate to the Dashboard.
2. Observe the alignment of the radio buttons.

## Expected Behavior
The radio buttons should be properly aligned as per the Tailwind CSS specifications.
![image](https://github.com/Arindam200/makaut_buddy/assets/109217591/3c72527d-ca49-4f3d-8cf8-c2f669f2bf2f)
## Actual Behavior
The radio buttons are misaligned due to conflicting CSS classes from Tailwind and Material-UI.
![image](https://github.com/Arindam200/makaut_buddy/assets/109217591/7ecc5e10-2371-4f5d-a605-39fa27d80ec6)

#### Possible Solution
Investigate the CSS class conflicts between Tailwind and Material-UI and ensure that Tailwind classes are not being overwritten.

**Comment by Abhishek-90** [comment]
I would like to take it up!

**Comment by Arindam200** [comment]
Go Ahead @Abhishek-90

**Comment by Avinashshiyani** [comment]
Hello Arindam,

I propose converting the design from Figma to Tailwind CSS to ensure consistency and achieve a better UI implementation. I am willing to take on this task.

Looking forward to your feedback!

Best regards,
Avinash

**Comment by Arindam200** [comment]
Hey @Avinashshiyani 

We Don't currently have a design for that, According to the other section Can you make something?

**Comment by Arindam200** [comment]
Hey @Abhishek-90 Are you still working on this?

**Comment by Arindam200** [comment]
> Hello Arindam,
> 
> I propose converting the design from Figma to Tailwind CSS to ensure consistency and achieve a better UI implementation. I am willing to take on this task.
> 
> Looking forward to your feedback!
> 
> Best regards, Avinash

THe Error is due to MUI classes Overwriting the tailwind classes.

**Comment by Avinashshiyani** [comment]
> > Hello Arindam,
> > 
> > I propose converting the design from Figma to Tailwind CSS to ensure consistency and achieve a better UI implementation. I am willing to take on this task.
> > 
> > Looking forward to your feedback!
> > 
> > Best regards, Avinash
> 
> The Error is due to MUI classes Overwriting the tailwind classes. 

Please assign me the task so thai i can help

**Comment by Abhishek-90** [comment]
> Hey @Abhishek-90 Are you still working on this?

Yes @Arindam200 , I was otherwise involved with office work last week, will get it done by friday. Sorry for delay.

**Comment by Arindam200** [comment]
Okay @Abhishek-90, Feel Free to make a PR when you're done

**Comment by MyBaBB** [comment]
Do you still need this done.?   Tailwind and MUI clash sometimes,   I could probably adj. it.

**Comment by Arindam200** [comment]
Sure. 

Feel free to make a PR

**Comment by MyBaBB** [comment]
Cool, Thanks. I was looking for something to do, I noticed that has been on here for a while.   I will take a look.

**Comment by MyBaBB** [comment]
Thanks, let me know how if it works out.

**Comment by Arindam200** [comment]
Resolved
