### ISSUE TITLE
Add: open graph image

### ISSUE THREAD

**Issue by OlibhiaGhosh** [Arindam200/makaut_buddy#159]
## Description

Enhance link previews on social media by adding an Open Graph image to our Next.js project. This will improve the appearance of our links when shared on social media platforms like Facebook, Twitter, LinkedIn, etc. By including an Open Graph image, we can ensure that our content is visually appealing and more likely to attract clicks and engagement.

**Comment by Arindam200** [comment]
Great Suggestion, @OlibhiaGhosh 

Would you like to work on this?

**Comment by OlibhiaGhosh** [comment]
Sure @Arindam200 . Please assign this to me.

**Comment by Arindam200** [comment]
Awesome, Go ahead @OlibhiaGhosh

**Comment by OlibhiaGhosh** [comment]
Sorry for the delay!

I will send the PR within 3 to 4 days

**Comment by Arindam200** [comment]
Fixed
