### ISSUE TITLE
feat: Add `MONGODB_URI` to README and `.env.example`

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#165]
## Description: 
Update the README.md and .env.example files to include the MONGODB_URI environment variable for MongoDB connection.

## Tasks:

- Add MONGODB_URI=YOUR_MONGODB_CONNECTION_URI to the .env section of the `README`.
- Add MONGODB_URI=YOUR_MONGODB_CONNECTION_URI to the `.env.example` file.
- Mention MongoDb Account in the Prerequisites section of README.

This will help developers set up the project correctly.

**Comment by SartHak-0-Sach** [comment]
Hi @Arindam200, I would love to work on this issue, please assign me this and allow me to contribute to it

**Comment by Arindam200** [comment]
Go Ahead!

**Comment by SartHak-0-Sach** [comment]
Ok thanks a lot😇

**Comment by SartHak-0-Sach** [comment]
Thank you for merging my pull request @Arindam200 and helping me get started in hacktoberfest'24, you can close this issue now👍🏻
