### ISSUE TITLE
fix: Remove "Add Resources" button from right side of dashboard to maintain consistency

### ISSUE THREAD

**Issue by OlibhiaGhosh** [Arindam200/makaut_buddy#169]
# Description
Two **Add Resources** buttons on the dashboard create inconsistency and are also not visually appealing when no resources are there in any section. Thus to maintain consistency remove the **Add Resources** button from the right sight

# Screenshot 
Here's the screenshot of the button to be deleted
![image](https://github.com/user-attachments/assets/62490712-7bb5-4fd0-a1b0-26111dd111ad)

**Comment by OlibhiaGhosh** [comment]
I would like to work on this!

**Comment by Arindam200** [comment]
Thanks for Pointing this out @OlibhiaGhosh !

Go ahead ! 🚀
