### ISSUE TITLE
(fix): The Alignment of two Assets 

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#18]
## Description

The alignment of assets on the Hero page and Features page is currently misaligned, leading to a visual inconsistency in our project.

### Current Behavior:

On the Hero page, assets are not aligning as intended, causing a lack of visual harmony.
The Features page also exhibits a different alignment, compounding the inconsistency.

### Screenshot:

![image](https://github.com/Arindam200/makaut_buddy/assets/109217591/edada398-31b2-43df-9abe-e48b232b8410)

### Expected Behavior:

Assets on both the Hero and Features pages should align correctly, creating a cohesive and visually pleasing presentation.

![image](https://github.com/Arindam200/makaut_buddy/assets/109217591/566c444f-da66-415b-a613-1906694408f4)

### Relevant Design Files:

Check out our [Design File](https://www.figma.com/file/NXmDxbLgtpXVT6ZMhAVax7/MAKAUT-Buddy?type=design&node-id=0%3A1&mode=design&t=UGftAjtCC4f96bmE-1)

**Comment by mehulrnsit** [comment]
Hey @Arindam200 I would like to take this up

**Comment by Arindam200** [comment]
Go Ahead @mehulrnsit !

**Comment by mehulrnsit** [comment]
@Arindam200 Please let me know if any more changes are required
