### ISSUE TITLE
(fix): Navbar Active Element

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#19]
## Description

Currently, there is an issue with the navigation bar where the active element is not correctly highlighted based on the page the user is on. Specifically, when the user is on the Home page, the "Home" navigation item is not active, and when the user is on the Features page, the "Features" navigation item is also not active. 

This creates confusion for users trying to determine their current location within the website

## Expected Behavior:

The expected behavior is that the navigation bar should accurately reflect the page the user is on. When the user is on the Home page, the "Home" navigation item should be active, and when the user is on the Features page, the "Features" navigation item should be active. 

This visual cue helps users understand their current position within the website's structure.

## Additional Information:

- The website is built using Next.js and utilizes [NextUI](https://nextui.org/docs) components.
- The issue should be resolved in a way that is compatible with NextUI components.

**Comment by fandok** [comment]
Hi, I have experience in nextjs but never using the NextUI components. Is it possible that i looked into this issue? thanks

**Comment by Arindam200** [comment]
Hey @fandok ! It's completely okay! 

Basically, NextUi provides on prop `isActive` for the NavItems. 

But you can do it manually as well, So Go ahead!

**Comment by fandok** [comment]
> Hey @fandok ! It's completely okay!
> 
> Basically, NextUi provides on prop `isActive` for the NavItems.
> 
> But you can do it manually as well, So Go ahead!

Thank you so much ! I'll see what I can do

**Comment by fandok** [comment]
By the way, do you want for each navbar redirects to another page or another sections the same page?

**Comment by Arindam200** [comment]
It should redirect to another section of the same page. 

You can skip Dashboard one! As we haven't decided much about that!

**Comment by fandok** [comment]
Hi I finished the solution. Lmk if it is expected or not for that. Thank you

**Comment by r0ld3x** [comment]
assign me if still not done yet
