### ISSUE TITLE
(fix): Modify the README.md file for better understanding

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [Arindam200/makaut_buddy#21]
## Issue Title

> (bug) : Ordering issue In README.md the description of `Environment Variables` . 

## Issue Description
> There it is said to first add the .env file but it will be better if anyone first sign in to `https://clerk.com/` then add .env file in him/her local setup then complete the whole setup to run the project and a screenshot of the ui of clerk.com with proper steps in order should be given for better understanding of the contributors.

## Expected Behavior
> stepwise description of how to setup with providing screenshots.

## Actual Behavior
> no screenshots are provided and issues are there in terms of ordering.

## Steps to Reproduce 
>  *relevant steps required to reproduce this issue.*

1. go to https://github.com/Arindam200/makaut_buddy#readme
2.go to  [Environment Variables](https://github.com/Arindam200/makaut_buddy#environment-variables)
3.See the ordering.

## Version Information
>  
- OS: Ubuntu 22.04.3 LTS
- Browser - chrome
- Version - 117.0.5938.132

**Comment by Arindam200** [comment]
Thanks for Creating this issue @subhadeepbanerjee2003  ! 

Do you want to work on this?

**Comment by subhadeepbanerjee2003** [comment]
Yes

**Comment by Arindam200** [comment]
Great! Go Ahead!

**Comment by Arindam200** [comment]
@subhadeepbanerjee2003 Are you working on this?

**Comment by subhadeepbanerjee2003** [comment]
> @subhadeepbanerjee2003 Are you working on this?

yes
