### ISSUE TITLE
(fix): Clicking Sign up button in navbar landing to Sign in page 

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [Arindam200/makaut_buddy#23]
## Issue Title

> (fix): Clicking Sign up button in navbar landing to Sign in page .

## Issue Description
> Clicking Sign up button in navbar landing to Sign in page , so it may conveya false information to the user.

## Expected Behavior
> The text `Sign up` should be changed to `Sign in` for better understanding of the user.

## Actual Behavior
> Clicking Sign up button in navbar landing to Sign in page 

## Steps to Reproduce 
> *steps required to reproduce this issue.*

1. go to the [makaut-buddy.vercel.app](https://makaut-buddy.vercel.app/)
2. go to the navbar and click on the `Sign up` button you can see it is landing to the sign in page

## Screenshots 
![Screenshot from 2023-10-04 12-05-54](https://github.com/Arindam200/makaut_buddy/assets/116381157/715d11ac-3c9b-4f06-aa5d-b06a0d13331c)

![Screenshot from 2023-10-04 12-06-08](https://github.com/Arindam200/makaut_buddy/assets/116381157/ebe2e738-2600-4f90-a9d8-de4ee4da0028)

## Version Information
> 
- OS: Ubuntu 22.04.3 LTS
- Browser - chrome
- Version - 117.0.5938.132

**Comment by Arindam200** [comment]
Do you want to Work on this?

**Comment by subhadeepbanerjee2003** [comment]
Yes I will work

**Comment by Arindam200** [comment]
Ok Great! Go Ahead!

**Comment by Arnav7107** [comment]
Hey @Arindam200, this issue has been resolved do you want me to make a PR??
