### ISSUE TITLE
(fix): Dropdowns in the FAQ section

### ISSUE THREAD

**Issue by Swpn0neel** [Arindam200/makaut_buddy#24]
## Issue Title

 Dropdowns in the FAQ section

## Issue Description
 When the dropdown to any question is clicked in the FAQ section the whole footer section and the left part of the section is moving up and down with the question.

## Expected Behavior
 Only the right side questions section should move and respond to the animation.
## Actual Behavior
 When the dropdown to any question is clicked in the FAQ section the whole footer section and the left part of the section is moving up and down with the question.

## Steps to Reproduce 
 Keep this in mind:
1.  This can be fixed by fixing the height of that section.
2.  Maintain the responsiveness of the section.
3.  Don't alter the alignment or existing design.

**Comment by Rehan52004** [comment]
Please assign me this issue.

**Comment by Arindam200** [comment]
Go Ahead! @Rehan52004 !

**Comment by nikhilgarg26** [comment]
@Arindam200 can you assign me this issue ?

**Comment by Arindam200** [comment]
Go ahead!

**Comment by nikhilgarg26** [comment]
sure

**Comment by nikhilgarg26** [comment]
i have created the PR any changes are needed on it or not ?
