### ISSUE TITLE
(fix): pointer not visible on hover over Features section

### ISSUE THREAD

**Issue by nikhilgarg26** [Arindam200/makaut_buddy#30]
## Issue Title
(fix): Hover on Features section in navbar

## Issue Description
When we hover on the Features button in navbar the pointer icon is not displayed but in other buttons it is displayed.

## Expected Behavior
To show a pointer icon on hover.

## Actual Behavior
Just showing the normal text icon on hover.

## Steps to Reproduce 

1.Open the website and hover over it.

https://github.com/Arindam200/makaut_buddy/assets/116938919/995eef95-3635-4828-949c-e7331ef5578a

**Comment by Arindam200** [comment]
Do you want to work on this?

**Comment by nikhilgarg26** [comment]
yes you can assign me this

**Comment by Arindam200** [comment]
Go Ahead!
