### ISSUE TITLE
Dockerize this project

### ISSUE THREAD

**Issue by Ayaan49** [Arindam200/makaut_buddy#35]
## Issue Title
Feat: Dockerize this project

## Issue Description
I am interested in contributing to this project, and I believe dockerizing the project can be a valuable addition. This issue is a request for assistance with dockerizing the project. 

## Expected Behavior
I expect that by dockerizing the project, it will become easier for contributors to set up a development environment, test the application, and deploy it consistently across various environments.

## Actual Behavior
Currently, the project is not dockerized, and I would like guidance from the maintainers or other contributors on how to create a Dockerfile and configure Docker containers for the project.

## Steps to Reproduce 
To reproduce this issue:
1. Clone the GitHub repository. 
2. Attempt to create a Dockerfile and configure a Docker container for the project.
3. Encounter challenges and the need for guidance on dockerizing the project.

**Comment by Ayaan49** [comment]
Hey @Swpn0neel , I thought you were going to assign this issue to me since I raised it. Now some other folk has pulled a PR :(

**Comment by Swpn0neel** [comment]
Hey @Ayaan49, extremely sorry for the misunderstanding. Please, send the PR, we'll accept it !

**Comment by Ayaan49** [comment]
No worries @Swpn0neel!! I will send a PR by tomorrow.

**Comment by Swpn0neel** [comment]
Thanks for contributing!! @Ayaan49 Closing the issue.
