### ISSUE TITLE
this is the problem 

### ISSUE THREAD

**Issue by rayAritra** [Arindam200/makaut_buddy#58]
## Issue Title

the problem is this

## Issue Description
I have identified this problem
## Expected Behavior
this is not working properly
## Actual Behavior
> *what is the **actual** behavior?*

## Steps to Reproduce 
> *provide relevant steps and/or prerequisites required to reproduce this issue.*

1.
2.
3.

## Version Information
> *Provide the version information.*

**Comment by Arindam200** [comment]
Good Work!

**Comment by rayAritra** [comment]
I would like to work on this...
