### ISSUE TITLE
feat: adding a new feature

### ISSUE THREAD

**Issue by RitochitGhosh** [Arindam200/makaut_buddy#60]
## Decorating the page

> Adding some more features in the website

## Issue Description
> It is a description

## Expected Behavior
> *what is the **expected** behavior?*

## Actual Behavior
> *what is the **actual** behavior?*

## Steps to Reproduce 
> *provide relevant steps and/or prerequisites required to reproduce this issue.*

1.
2.
3.

## Version Information
> *Provide the version information.*

**Comment by RitochitGhosh** [comment]
I want to work on this issue

**Comment by Arindam200** [comment]
Good Work!
