### ISSUE TITLE
feat: add new feature

### ISSUE THREAD

**Issue by TamojitMandal** [Arindam200/makaut_buddy#62]
## Issue Title

> *i want to add a new feature on this project.*

## Issue Description
> *provide a brief description of the issue*

## Expected Behavior
> *what is the **expected** behavior?*

## Actual Behavior
> *what is the **actual** behavior?*

## Steps to Reproduce 
> *provide relevant steps and/or prerequisites required to reproduce this issue.*

1.
2.
3.

## Version Information
> *Provide the version information.*

**Comment by TamojitMandal** [comment]
I would like to work on this

**Comment by Arindam200** [comment]
Great Work!
