### ISSUE TITLE
Add Mathematics(Matrices) 1st Semester resources

### ISSUE THREAD

**Issue by Swpn0neel** [Arindam200/makaut_buddy#64]
## Issue Title

> Add Maths(Matrices) 1st semester resources

## Issue Description
> Add Maths(Matrices) 1st semester resources in "src/app/components/Tabs/Data.jsx"

## Video Links
> Extract the relevant videos from the playlist and add it to Data.jsx : https://www.youtube.com/playlist?list=PLU6SqdYcYsfINU_Y9CMp1pZ827ZB1U-Xn

**Comment by Arindam200** [comment]
Note: 

The Format will be like this: 

```javascript
          {       
            key: 00 , // the next number
            heading: "The Title",
            description:
              "add a small description.",
            link: "https://www.youtube.com/xyz",
          },
```

**Comment by RitochitGhosh** [comment]
I, @janasounak & @dharasritama want to work on this project as a team

**Comment by Swpn0neel** [comment]
Assigned @RitochitGhosh.

@janasounak & @dharasritama have to comment individually to get assigned.

**Comment by janasounak** [comment]
I'd like to work on this project as a part of the team of @RitochitGhosh .

**Comment by dharasritama** [comment]
I'd like to work on this project as a part of the team of @RitochitGhosh .

**Comment by Swpn0neel** [comment]
Go ahead @dharasritama !!

**Comment by dharasritama** [comment]
Adding resources to mathematics section (Matrices) has been completed.
