### ISSUE TITLE
Add Chemistry(Thermdynamics) 1st Semester resources

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#65]
## Issue Title
Add Chemistry 1st semester resources

## Issue Description
Add Chemistry 1st semester resources in "src/app/components/Tabs/Data.jsx"

## Video Links
Extract the relevant videos from the playlist and add it to Data.jsx : https://www.youtube.com/playlist?list=PLm_MSClsnwm9p_yaZ8zIW1LxkK7_n98gD

Note:

The Format will be like this:

```javascript
          {       
            key: 00 , // the next number
            heading: "The Title",
            description:
              "add a small description.",
            link: "https://www.youtube.com/xyz",
          },
```

**Comment by TamojitMandal** [comment]
I want to work on this project.

**Comment by TanayRoy18** [comment]
I want to work on this with @TamojitMandal

**Comment by Swpn0neel** [comment]
Go ahead @TanayRoy18 and @TamojitMandal

**Comment by Aindrila-biswas** [comment]
I want to work on this with @TamojitMandal and @TanayRoy18

**Comment by Swpn0neel** [comment]
Go ahead!! @Aindrila-biswas

**Comment by suchanaGhosh** [comment]
I want to work on this with @TamojitMandat,@Aindrila-biswas and @TanayRoy18

**Comment by Swpn0neel** [comment]
Go ahead @suchanaGhosh

**Comment by TamojitMandal** [comment]
Adding resources to chemistry section (Thermodynamics) has been completed.
