### ISSUE TITLE
Add Electronics 1st Semester Resources

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#66]
## Issue Title
Add Electronics 1st semester resources

## Issue Description
Add Electronics 1st semester resources in "src/app/components/Tabs/Data.jsx"

## Video Links
Extract the relevant videos from the playlist and add it to Data.jsx : https://www.youtube.com/playlist?list=PL3qvHcrYGy1uF5KAGntUITTJ85Dm3Dtdy

Note:

The Format will be like this:

```javascript
          {       
            key: 00 , // the next number
            heading: "The Title",
            description:
              "add a small description.",
            link: "https://www.youtube.com/xyz",
          },
```

**Comment by rayAritra** [comment]
I want to work on this project..

**Comment by Dibyendukundu04** [comment]
I want to work on this with @rayAritra

**Comment by OlibhiaGhosh** [comment]
I want to work on this with @rayAritra and @Dibyendukundu04

**Comment by Arindam200** [comment]
Assigned to @rayAritra @Dibyendukundu04 @OlibhiaGhosh ! 

All the Best!

**Comment by AanirbanNandi** [comment]
I want to work on this with @rayAritra,@OlibhiaGhosh and @Dibyendukundu04

**Comment by Arindam200** [comment]
Go Ahead @AanirbanNandi !

**Comment by Dibyendukundu04** [comment]
We have added 25 videos in total, among these we have added 15 videos today.

**Comment by Arindam200** [comment]
Great work Folks! @Dibyendukundu04 @rayAritra @OlibhiaGhosh ! 

Keep Contributing!
