### ISSUE TITLE
(feat): Add Issue & Pull Request Templates

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/makaut_buddy#9]
## Issue Description:
Add templates for issues and pull requests to improve clarity, consistency, and efficiency in our repository's contributions. These templates will guide contributors and help us maintain better documentation.

## Tasks:

- Create an issue template that includes fields for title, description, expected behavior, actual behavior, steps to reproduce, and version information.
- Create a pull request template that includes fields for a brief description, related issue(s), and any additional context.
- Document these templates in the repository's README or CONTRIBUTING.md file to inform potential contributors.

**Comment by gifmackenzie** [comment]
@Arindam200 I can create these templates in CONTRIBUTING.md 👍

**Comment by Arindam200** [comment]
Go Ahead!
